FROM centos:8.2.2004
ARG _UID=6213
ARG _GID=11429
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
ENV LANG=en_US.utf-8
USER root

RUN yum install -y \
    epel-release

RUN yum install --enablerepo=PowerTools -y \
    sudo \
    git \
    wget \
    fakeroot \
    ncurses-devel \
    rpm-build doxygen \
    graphviz \
    numactl-devel \
    libiscsi-devel \
    make \
    gcc \
    CUnit-devel \
    libaio-devel \
    openssl-devel \
    libuuid-devel \
    gcc-c++ \
    python36 \
    meson

RUN set -eux; \
    wget https://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox; \
    sudo rpm --import RPM-GPG-KEY-Mellanox; \
    wget https://linux.mellanox.com/public/repo/mlnx_ofed/5.3-1.0.0.1/rhel8.2/mellanox_mlnx_ofed.repo -P /etc/yum.repos.d/; \
    yum install mlnx-ofed-basic-user-only -y 

RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN mkdir -p $_HOME
RUN groupadd -f -g "$_GID" "$_LOGIN"
RUN useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "$_LOGIN"
RUN chown $_LOGIN $_HOME
RUN yum clean all

SHELL ["/bin/bash"]
USER "${_LOGIN}"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]
