#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../../../../)

TEST_FILE = vbdev_lvol_esnap_ut.c

include $(SPDK_ROOT_DIR)/mk/spdk.unittest.mk
